name: Opam Regular - Build and Test

env:
  OPAM_PACKAGE: "your_example"

on:
  push:
    branches:
      - main
      - v*
      - feature-*
    tags:
      - v*
  # ... or trigger manually from GitHub web interface
  workflow_dispatch:

jobs:
  setup-dkml:
    # uses: "diskuv/dkml-workflows/.github/workflows/setup-dkml.yml@v1"
    uses: "diskuv/dkml-workflows-prerelease/.github/workflows/setup-dkml.yml@feature-gitlab"
    with:
      OCAML_COMPILER: 4.12.1
      CACHE_PREFIX: test1

  build:
    timeout-minutes: 90 # 1.5 hours

    # Wait until `setup-dkml` is finished
    needs: setup-dkml

    # Five (5) build environments will be available. You can include
    # all of them or a subset of them.
    strategy:
      fail-fast: false
      matrix:
        include:
          - gh_os: windows-2019
            abi_pattern: win32-windows_x86
            dkml_host_abi: windows_x86
            opam_root: D:/.opam
            default_shell: msys2 {0}
            msys2_system: MINGW32
            msys2_packages: mingw-w64-i686-pkg-config
          - gh_os: windows-2019
            abi_pattern: win32-windows_x86_64
            dkml_host_abi: windows_x86_64
            opam_root: D:/.opam
            default_shell: msys2 {0}
            msys2_system: CLANG64
            msys2_packages: mingw-w64-clang-x86_64-pkg-config
          - gh_os: macos-latest
            abi_pattern: macos-darwin_all
            dkml_host_abi: darwin_x86_64
            opam_root: /Users/runner/.opam
            default_shell: sh
          - gh_os: ubuntu-latest
            abi_pattern: manylinux2014-linux_x86
            dkml_host_abi: linux_x86
            opam_root: .ci/opamroot
            default_shell: sh
          - gh_os: ubuntu-latest
            abi_pattern: manylinux2014-linux_x86_64
            dkml_host_abi: linux_x86_64
            opam_root: .ci/opamroot
            default_shell: sh

    runs-on: ${{ matrix.gh_os }}
    name: build / ${{ matrix.abi_pattern }}

    # Use a Unix shell by default, even on Windows
    defaults:
      run:
        shell: ${{ matrix.default_shell }}

    env:
      # Remove Homebrew warnings for macOS
      HOMEBREW_NO_INSTALL_CLEANUP: 1

    steps:
      # BOILERPLATE START: setup-dkml
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install MSYS2 to provide Unix shell (Windows only)
        if: startsWith(matrix.dkml_host_abi, 'windows')
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msys2_system }}
          update: true
          install: >-
            ${{ matrix.msys2_packages }}
            wget
            make
            rsync
            diffutils
            patch
            unzip
            git
            tar

      - name: Download setup-dkml artifacts
        uses: actions/download-artifact@v3
        with:
          path: .ci/dist

      - name: Import build environments from setup-dkml
        run: |
          ${{ needs.setup-dkml.outputs.import_func }}
          import ${{ matrix.abi_pattern }}

      - name: Cache Opam downloads by host
        uses: actions/cache@v3
        with:
          path: ${{ matrix.opam_root }}/download-cache
          key: ${{ matrix.dkml_host_abi }}
      # BOILERPLATE END: setup-dkml

      # BOILERPLATE START: setup-dkml for Opam Regular workflow
      - name: Build and test the package
        env:
          opam_root:                "${{ matrix.opam_root }}"
          exe_ext:                  "${{ matrix.exe_ext }}"
          dkml_host_abi:            "${{ matrix.dkml_host_abi }}"
          abi_pattern:              "${{ matrix.abi_pattern }}"
        run: ci/build-test.sh --opam-package your_example.opam --executable-name your_example

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.dkml_host_abi }}
          path: dist/
      # BOILERPLATE END: setup-dkml for Opam Regular workflow

  #--------
  # Release
  #--------

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed for softprops/action-gh-release@v1
    # Wait until `build` complete
    needs:
      - build
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: dist

      - name: Remove setup artifacts
        run: rm -rf setup-*
        working-directory: dist

      - name: Restructure multi-ABI directories
        run: ci/prepare-release.sh

      - name: Release (only when Git tag pushed)
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            _release/*

      - name: Remove unneeded artifacts from GitHub Storage
        uses: geekyeggo/delete-artifact@v1
        with:
          failOnError: false
          name: |
            setup-dkml-macos-darwin_all
            setup-dkml-manylinux2014-linux_x86
            setup-dkml-manylinux2014-linux_x86_64
            setup-dkml-win32-windows_x86
            setup-dkml-win32-windows_x86_64
